# Generated by Django 3.2.16 on 2022-12-21 20:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='https://images.pexels.com/photos/8024968/pexels-photo-8024968.jpeg?auto=compress&cs=tinysrgb&w=600', max_length=255, verbose_name='image'),
        ),
    ]
